apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: text-generator-pipeline
description: Pipeline for deploying the text generator application
serialPipeline:
  stages:
    - targetId: dev
      profiles:
        - dev
      strategy:
        standard: {}
    - targetId: prod
      profiles:
        - prod
      strategy:
        standard: {}
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Development environment
requireApproval: true
gke:
  cluster: projects/kunal-ica1/locations/us-central1-a/clusters/my-cluster
 
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: production environment
requireApproval: true
gke:
  cluster: projects/kunal-ica1/locations/us-central1-a/clusters/my-cluster

