apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: text-generator
build:
  artifacts:
    - image: gcr.io/ethereal-smoke-422723-i0/text-generator
  googleCloudBuild:
    projectId: ethereal-smoke-422723-i0
deploy:
  kustomize:
    paths:
      - ./k8s
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
          - ./k8s/overlays/dev
  - name: prod
    deploy:
      kustomize:
        paths:
          - ./k8s/overlays/prod
