apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-generator
  template:
    metadata:
      labels:
        app: text-generator
    spec:
      containers:
      - name: text-generator
        image: gcr.io/ethereal-smoke-422723-i0/text-generator:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: API_KEY
          value: AIzaSyAcCFqcSUUsXNJYcBw0oPdlaLEitlxiyfc